### PR TITLE
feat: upgrade to Tauri 2.0 Beta

### PR DESCRIPTION
**Pull request by clearlysid**
Not an urgent PR, but wanted to keep this open so we don't forget. Things that don't work / haven't been tested:

- [x] Tray menu
- [x] GIF encoding
- [x] Autostart plugin
- [x] Global shortcut

### CODE REVIEW

**Comment by clearlysid** [comment]
Fixed the dragging bug and global shortcuts.

**Comment by clearlysid** [comment]
Now, I think the only remaining thing to work on is file access not being granted to the frontend. Which causes preview to not show in the editor. Pretty sure it is some small premissions issue. Will debug some more.

**Comment by clearlysid** [comment]
ALL DONE 🥳

Builds and works as expected, GIFs encode perfectly too and preview is visible.

HM-240408-0224PM

**Review by anubhavitis — APPROVED** [review]
LGTM

**Comment by clearlysid** [comment]
@RohanPunjani @Pranav2612000 when building this PR for the first time you will have to clear both your cargo and node caches to ensure this builds without any errors.

1. cd into `src-tauri` and run `cargo clean`
2. delete `yarn.lock` file and `node_modules` folder
3. run `yarn install` in the root dir
4. finally run `yarn tauri dev` as normal and it will build

This is only a one time step to flush the caches, from this point it will work as normal only.

**Pull request merged**
