### PR TITLE
feat: improves UI for the Editor window 

### LINKED ISSUE #64: If the capture area is too tall, the Editor controls go off-screen
If we try recording a very tall aspect ratio GIF (like for eg. an iPhone mockup) then the resulted Editor window created is very tall and often gets cut off on laptop screens, making it impossible to export the GIFs.

We have to set a max and min height + width and constrain the preview correctly to account for this situation.

### PR DESCRIPTION
**Pull request by clearlysid**
Will fix #64

### CODE REVIEW

**Comment by clearlysid** [comment]
GIF 2024-05-02 at 11-59-41 PM

improves the "loading" experience and sizing of the Editor window.

**Review by Pranav2612000 — APPROVED** [review]

**Comment by RohanPunjani** [comment]
While running `yarn tauri dev` on Windows:

Facing the following issue:
image

**Comment by clearlysid** [comment]
Ugh, fixing.

**Comment by clearlysid** [comment]
Done.

**Comment by clearlysid** [comment]
@RohanPunjani merged fix to main as well. Take a pull and try again?

**Comment by RohanPunjani** [comment]
The fix is working on windows for this branch.

But when I took a pull from main, I am still facing the same issue!

**Pull request merged**
