### PR TITLE
feat/multithreaded GIF encoding

### PR DESCRIPTION
**Pull request by clearlysid**
this PR refactors the `export_handler` function and makes it so the encoding of the final GIF is spread across multiple threads. We hope to gain some significant performance gains by doing this, once all the other issues are resolved.

### CODE REVIEW

**Comment by clearlysid** [comment]
There are a few things I would like to achieve before we merge this PR:

1. split the `export_handler` into smaller, easily manageable functions.
2. solve abnormally high CPU consumption (attached SS) — for long GIFs, this often gets pinned at 600-700% CPU on my M3 macbook 💀

Screenshot 2024-04-08 at 10 28 49 AM

**Comment by clearlysid** [comment]
Oh also, I think the Tauri main thread is also being utilized for encoding which causes the Helmer Micro UI to completely freeze up 💀

**Comment by anubhavitis** [comment]
I'll look into these today:
-  split the export_handler into smaller, easily manageable functions.
- solve abnormally high CPU consumption (attached SS) — for long GIFs, this often gets pinned at 600-700% CPU on my M3 macbook 💀


Also, this one was miss since I wasn't using the UI :3 Will look into this. 
- Tauri main thread is also being utilized for encoding which causes the Helmer Micro UI to completely freeze up 💀

**Review by anubhavitis — APPROVED** [review]
LGTM

**Pull request merged**
